# Generated by Django 4.2.16 on 2025-09-29 16:48

import apiary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiary',
            name='hive_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Qtd. de colmeias vinculadas'),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Localização (cidade/estado)'),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiaries', to=settings.AUTH_USER_MODEL, verbose_name='Responsável/Proprietário'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='acquisition_date',
            field=models.DateField(verbose_name='Data de aquisição'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='acquisition_method',
            field=models.CharField(choices=[('compra', 'Compra'), ('troca', 'Troca'), ('divisao', 'Divisão'), ('captura', 'Captura'), ('doacao', 'Doação')], max_length=20, verbose_name='Método de aquisição'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='apiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hives', to='apiary.apiary', verbose_name='Meliponário/Apiário'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='identification_number',
            field=models.CharField(default=apiary.models.generate_hive_identifier, editable=False, max_length=20, unique=True, verbose_name='N. de identificação'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='last_review_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data da última revisão'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='origin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Origem da colmeia'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='popular_name',
            field=models.CharField(max_length=255, verbose_name='Nome popular'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hives', to='apiary.species', verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='hive',
            name='status',
            field=models.CharField(choices=[('producao', 'Em produção'), ('observacao', 'Em observação'), ('orfa', 'Órfã'), ('morta', 'Morta'), ('doadavendida', 'Doada/Vendida'), ('perdida', 'Perdida')], default='producao', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='brood_level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Cria'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='colony_strength',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Força da colônia'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='food_level',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Alimento/Reservas'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='apiary.hive', verbose_name='Colmeia'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='hive_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso da colmeia'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='management_description',
            field=models.TextField(blank=True, verbose_name='Descrever manejo(s) realizado(s)'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='queen_seen',
            field=models.BooleanField(default=False, verbose_name='Rainha vista'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='review_date',
            field=models.DateTimeField(verbose_name='Data da revisão'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='temperament',
            field=models.CharField(choices=[('muito_mansa', 'Muito mansa'), ('mansa', 'Mansa'), ('media', 'Média'), ('arisca', 'Arisca'), ('agressiva', 'Agressiva')], max_length=20, verbose_name='Temperamento'),
        ),
        migrations.AlterField(
            model_name='revisionattachment',
            name='file',
            field=models.FileField(upload_to='revision_attachments/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='revisionattachment',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='apiary.revision', verbose_name='Revisão'),
        ),
        migrations.AlterField(
            model_name='species',
            name='characteristics',
            field=models.TextField(blank=True, verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='species',
            name='default_temperament',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Temperamento padrão'),
        ),
        migrations.AlterField(
            model_name='species',
            name='group',
            field=models.CharField(choices=[('apis_mellifera', 'Apis mellifera'), ('sem_ferrao', 'Sem ferrão')], max_length=20, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='species',
            name='popular_name',
            field=models.CharField(max_length=255, verbose_name='Nome popular'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(max_length=255, verbose_name='Nome científico'),
        ),
        migrations.AlterField(
            model_name='species',
            name='states',
            field=models.JSONField(blank=True, default=list, help_text='Lista das UFs onde a espécie é encontrada', verbose_name='UFs'),
        ),
    ]
