# Generated by Django 4.2.16 on 2025-09-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0002_alter_apiary_hive_count_alter_apiary_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='brood_level',
            field=models.CharField(choices=[('nenhuma', 'Nenhuma'), ('pouca', 'Pouca'), ('moderada', 'Moderada'), ('abundante', 'Abundante')], max_length=20, verbose_name='Cria'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='colony_strength',
            field=models.CharField(choices=[('fraca', 'Fraca'), ('media', 'Média'), ('forte', 'Forte')], max_length=20, verbose_name='Força da colônia'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='food_level',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('pouco', 'Pouco'), ('moderado', 'Moderado'), ('abundante', 'Abundante')], max_length=20, verbose_name='Alimento/Reservas'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='management_description',
            field=models.TextField(blank=True, verbose_name='Descreva manejo(s) realizado(s)'),
        ),
    ]
