# Generated by Django 4.2.16 on 2025-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiary", "0003_remove_revision_management_performed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revision",
            name="brood_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nenhuma", "Nenhuma"),
                    ("pouca", "Pouca"),
                    ("moderada", "Moderada"),
                    ("abundante", "Abundante"),
                ],
                max_length=20,
                verbose_name="Cria",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="colony_strength",
            field=models.CharField(
                blank=True,
                choices=[("fraca", "Fraca"), ("media", "Média"), ("forte", "Forte")],
                max_length=20,
                verbose_name="Força da colônia",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="food_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nenhum", "Nenhum"),
                    ("pouco", "Pouco"),
                    ("moderado", "Moderado"),
                    ("abundante", "Abundante"),
                ],
                max_length=20,
                verbose_name="Alimento/Reservas",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="pollen_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nenhum", "Nenhum"),
                    ("pouco", "Pouco"),
                    ("moderado", "Moderado"),
                    ("abundante", "Abundante"),
                ],
                max_length=20,
                verbose_name="Pólen",
            ),
        ),
        migrations.AlterField(
            model_name="revision",
            name="temperament",
            field=models.CharField(
                blank=True,
                choices=[
                    ("muito_mansa", "Muito mansa"),
                    ("mansa", "Mansa"),
                    ("media", "Média"),
                    ("arisca", "Arisca"),
                    ("agressiva", "Agressiva"),
                ],
                max_length=20,
                verbose_name="Temperamento",
            ),
        ),
    ]
