# Generated by Django 4.2.16 on 2025-10-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiary", "0004_alter_revision_brood_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hive",
            name="next_division_date",
            field=models.DateField(
                blank=True,
                help_text="Data planejada para a próxima divisão da colmeia.",
                null=True,
                verbose_name="Data da próxima divisão",
            ),
        ),
    ]
