# Generated by Django 4.2.16 on 2025-10-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiary", "0005_hive_next_division_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="hive",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="hive_photos/",
                verbose_name="Foto da colmeia",
            ),
        ),
        migrations.AddField(
            model_name="hive",
            name="position",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Posição no meliponário"
            ),
        ),
        migrations.AlterField(
            model_name="revisionattachment",
            name="file",
            field=models.ImageField(
                upload_to="revision_attachments/", verbose_name="Imagem"
            ),
        ),
    ]
