# Generated by Django 4.2.16 on 2025-10-01 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apiary", "0006_hive_photo_hive_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nome"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
            ],
            options={
                "verbose_name": "Modelo de caixa",
                "verbose_name_plural": "Modelos de caixas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nome"),
                ),
            ],
            options={
                "verbose_name": "Cidade",
                "verbose_name_plural": "Cidades",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="hive",
            name="origin_hive",
            field=models.ForeignKey(
                blank=True,
                help_text="No caso de divisão, selecione a colmeia de origem.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_hives",
                to="apiary.hive",
                verbose_name="Colmeia de origem",
            ),
        ),
        migrations.AddField(
            model_name="hive",
            name="transfer_date",
            field=models.DateField(
                blank=True,
                help_text="Informe quando a colmeia capturada foi transferida para a caixa.",
                null=True,
                verbose_name="Data de transferência para a caixa",
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="feeding_energy_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Quantidade de alimento energético fornecido (ml ou g)",
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="feeding_energy_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xarope", "Xarope"),
                    ("mel_apis", "Mel de Apis"),
                    ("mel_asf", "Mel de ASF"),
                ],
                max_length=20,
                verbose_name="Tipo de alimento energético fornecido",
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="feeding_notes",
            field=models.TextField(
                blank=True, verbose_name="Observações específicas sobre a alimentação"
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="feeding_protein_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Quantidade de suplemento proteico fornecido (g)",
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="feeding_protein_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bombom_polen", "Bombom de Pólen"),
                    ("bombom_soja", "Bombom Soja"),
                    ("pasta_polen", "Pasta de Pólen"),
                    ("pasta_soja", "Pasta de Soja"),
                ],
                max_length=20,
                verbose_name="Tipo de alimento proteico fornecido",
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="harvest_notes",
            field=models.TextField(
                blank=True, verbose_name="Observações específicas sobre a colheita"
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="honey_harvest_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Quantidade de mel colhida (ml)",
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="pollen_harvest_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Quantidade de pólen colhida (g)",
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="propolis_harvest_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Quantidade de própolis colhida (g)",
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("rotina", "Revisão de rotina"),
                    ("divisao", "Divisão"),
                    ("tratamento", "Tratamento"),
                    ("alimentacao", "Alimentação"),
                    ("colheita", "Colheita"),
                ],
                default="rotina",
                max_length=20,
                verbose_name="Tipo de revisão",
            ),
        ),
        migrations.AddField(
            model_name="revision",
            name="wax_harvest_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Quantidade de cera colhida (g)",
            ),
        ),
        migrations.AlterField(
            model_name="hive",
            name="acquisition_date",
            field=models.DateField(
                verbose_name="No caso de compra, qual a data de aquisição"
            ),
        ),
        migrations.CreateModel(
            name="CreatorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome do criador"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Telefone (WhatsApp)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_profiles",
                        to="apiary.city",
                        verbose_name="Localização (cidade/estado)",
                    ),
                ),
                (
                    "species",
                    models.ManyToManyField(
                        blank=True,
                        related_name="creator_profiles",
                        to="apiary.species",
                        verbose_name="Espécies criadas",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Criador inscrito",
                "verbose_name_plural": "Criadores inscritos",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="hive",
            name="box_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hives",
                to="apiary.boxmodel",
                verbose_name="Modelo de caixa",
            ),
        ),
    ]
