# Generated by Django 4.2.16 on 2025-10-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiary", "0007_boxmodel_city_hive_origin_hive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hive",
            name="acquisition_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="No caso de compra, qual a data de aquisição",
            ),
        ),
    ]
