# Generated by Django 4.2.16 on 2025-10-02 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apiary", "0008_alter_hive_acquisition_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiary",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="creators",
                to="apiary.city",
                verbose_name="Localização (cidade/estado)",
            ),
        ),
        migrations.AlterField(
            model_name="apiary",
            name="location",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                verbose_name="Localização (cidade/estado)",
            ),
        ),
        migrations.AlterField(
            model_name="creatornetworkentry",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="creator_network_entries",
                to="apiary.city",
                verbose_name="Localização (cidade/estado)",
            ),
        ),
    ]
