# Generated by Django 4.2.16 on 2025-10-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0009_apiary_city_alter_apiary_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='management_performed',
            field=models.BooleanField(default=False, verbose_name='Houve manejo?'),
        ),
    ]
