# Generated by Django 4.2.16 on 2025-10-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0010_revision_management_performed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='management_performed',
        ),
    ]
