# Generated by Django 4.2.16 on 2025-10-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0011_remove_revision_management_performed'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='management_performed',
            field=models.BooleanField(default=False, verbose_name='Houve manejo?'),
        ),
    ]
