# Generated by Django 4.2.16 on 2025-10-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0012_revision_management_performed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='notes',
        ),
        migrations.AlterField(
            model_name='revision',
            name='management_description',
            field=models.TextField(blank=True, verbose_name='Descreva manejo(s) realizado(s) ou observações específicas'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='management_performed',
            field=models.BooleanField(default=False, verbose_name='Houve manejo? Ou observações específicas?'),
        ),
    ]
