# Generated by Django 4.2.16 on 2025-10-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiary', '0013_remove_revision_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='notes',
            field=models.TextField(blank=True, editable=False, verbose_name='Observações'),
        ),
    ]
