# Generated by Django 4.2.16 on 2025-02-14 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiary", "0014_revision_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiary",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="apiary_photos/",
                verbose_name="Foto do meliponário",
            ),
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Nome")),
                (
                    "start_month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mês de início",
                    ),
                ),
                (
                    "start_day",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Dia de início",
                    ),
                ),
                (
                    "end_month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mês de término",
                    ),
                ),
                (
                    "end_day",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Dia de término",
                    ),
                ),
            ],
            options={
                "ordering": ["start_month", "start_day"],
                "verbose_name": "Estação do ano",
                "verbose_name_plural": "Estações do ano",
            },
        ),
        migrations.CreateModel(
            name="MellitophilousPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "popular_name",
                    models.CharField(max_length=255, verbose_name="Nome popular"),
                ),
                (
                    "scientific_name",
                    models.CharField(max_length=255, verbose_name="Nome científico"),
                ),
                (
                    "pollen_supply",
                    models.CharField(
                        choices=[
                            ("baixo", "Baixo"),
                            ("medio", "Médio"),
                            ("alto", "Alta"),
                        ],
                        default="medio",
                        max_length=10,
                        verbose_name="Qtd. de pólen fornecido",
                    ),
                ),
                (
                    "nectar_supply",
                    models.CharField(
                        choices=[
                            ("baixo", "Baixo"),
                            ("medio", "Médio"),
                            ("alto", "Alta"),
                        ],
                        default="medio",
                        max_length=10,
                        verbose_name="Qtd. de néctar fornecido",
                    ),
                ),
                (
                    "flowering_seasons",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mellitophilous_plants",
                        to="apiary.season",
                        verbose_name="Estações em que floresce",
                    ),
                ),
            ],
            options={
                "ordering": ["popular_name", "scientific_name"],
                "unique_together": {("popular_name", "scientific_name")},
                "verbose_name": "Planta melitofílica",
                "verbose_name_plural": "Plantas melitofílicas",
            },
        ),
        migrations.CreateModel(
            name="QuickObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Informe no formato dd-mm-aaaa.",
                        verbose_name="Data",
                    ),
                ),
                (
                    "internal_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="quick_observations/internal/",
                        verbose_name="Foto interna",
                    ),
                ),
                (
                    "external_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="quick_observations/external/",
                        verbose_name="Foto externa",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "hive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_observations",
                        to="apiary.hive",
                        verbose_name="Colmeia",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-pk"],
                "verbose_name": "Observação rápida",
                "verbose_name_plural": "Observações rápidas",
            },
        ),
    ]
